version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/public/app/themes/justice'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
